config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  get "/home/about" => 'homes#about'

  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  attachment :image

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
       render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end
  
  def use
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= form_with model:@book, local: true do |f| %>
    	<% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this book from being saved:
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
　      <% end %>
      <% end %>
        <div class="form-group">
          <label class="book_title">Title</label>
          <%= f.text_field :title, class:'form-control book_title' %>
        </div>
        <div class="form-group">
          <label class="book_opinion">Opinion</label>
          <%= f.text_area :body, class:'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class:'btn btn-success' %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <ul class="error_explanation">
     <li><%= message %></li>
    </ul>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
	          <th>name</th>
	          <th><%= current_user.name %></th>
          </tr>
          <tr>
	          <th>introduction</th>
	          <th><%= current_user. introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <h6 class="book_title">Title</h6>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h6 class="book_opinion">Opinion</h6>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class:'btn btn-success' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @book, local:true do |f| %>
<h4>title</h4>
<%= f.text_field :title %>
<h4>body</h4>
<%= f.text_area :body %>
<%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
	          <th>name</th>
	          <th><%= @book.user.name %></th>
          </tr>
          <tr>
	          <th>introduction</th>
	          <th><%= @book.user. introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(@book.user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book_new, local:true do |f| %>
        <div class="form-group">
          <h6 class="book_title">Title</h6>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h6 class="book_opinion">Opinion</h6>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class:'btn btn-success' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
  	  <h2>Book detail</h2>
  	  <table class="table table-hover table-inverse">
  	    <tbody>
  		    <tr>
           <td class='attachment user profile_image fallback'>
             <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
             <%= link_to @book.user.name, user_path(@book.user_id) %>
           </td>
           <td><%= link_to @book.title, book_path(@book.id) %></td>
           <td><%= @book.body %></td>
           <td>
             <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success'  %>
              <%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-sm btn-success' %>
            <% end %>
           </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/use.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
	          <th>name</th>
	          <th><%= current_user.name %></th>
          </tr>
          <tr>
	          <th>introduction</th>
	          <th><%= current_user. introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book_new, local:true do |f| %>
        <div class="form-group">
          <h6 class="book_title">Title</h6>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h6 class="book_opinion">Opinion</h6>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class:'btn btn-success' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
  	  <h2>Book detail</h2>
  	  <table class="table table-hover table-inverse">
  	    <tbody>
  		    <tr>
           <td class='attachment user profile_image fallback'>
             <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
             <%= link_to @book.user.name, user_path(@book.user_id) %>
           </td>
           <td><%= link_to @book.title, book_path(@book.id) %></td>
           <td><%= @book.body %></td>
           <td>
             <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success'  %>
              <%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-sm btn-success' %>
            <% end %>
           </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
          <a class="navbar-brand p-3 text-white" href="/">Bookers</a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
             <% if user_signed_in? %>
             <li class="nav-item">
               <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-white' %>
             </li>
             <li >
              <%= link_to 'Users', users_path, class:'fas fa-users nav-link text-light' %>
             </li>
             <li class="nav-item">
               <%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-white'  %>
             </li>
             <li class="nav-item">
               <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
             </li>
             <% else %>
             <li class="nav-item">
               <a class="fas fa-home nav-link text-light" href="/"> Home</a>
             </li>
             <li>
               <a class="fas fa-link nav-link text-light" href="/home/about"> About</a>
             </li>
             <li class="nav-item">
               <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-white' %>
             </li>
             <li class="nav-item">
               <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
             </li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-white  pt-5 pb-4">
      <p class="text-center">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this book from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
　      <% end %>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class:'form-control name' %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:'form-control-file user_image' %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", class:'form-control introduction' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
	          <th>name</th>
	          <th><%= current_user.name %></th>
          </tr>
          <tr>
	          <th>introduction</th>
	          <th><%= current_user. introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <h6 class="book_title">Title</h6>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h6 class="book_opinion">Opinion</h6>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class:'btn btn-success' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
  	  <h2>Book detail</h2>
  	  <table class="table table-hover table-inverse">
  	    <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
            <th></th>
          </tr>
        </thead>
  	    <tbody>
  	      <% @users.each do |user| %>
  		      <tr>
             <td class='attachment user profile_image fallback'>
               <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
             </td>
             <td><%= user.name %></td>
             <td><%= link_to "Show", user_path(user.id) %></td>
             <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
	          <th>name</th>
	          <th><%= @user.name %></th>
          </tr>
          <tr>
	          <th>introduction</th>
	          <th><%= @user. introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <h6 class="book_title">Title</h6>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h6 class="book_opinion">Opinion</h6>
          <%= f.text_area :body %>
        </div>
        <%= f.submit 'Create Book', class:'btn btn-success'  %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @user.books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>